name: "Terraform"

on:
  push:
    branches:
      - main
  pull_request:

jobs: 
  terraform: 
    name: Terraform
    runs-on: ubuntu-latest
    env: 
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          SLACK_WEBHOOK_URL: "${{ secrets.SLACK_WEBHOOK_URL }}"
        
    steps: 
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        id: fmt
        name: "Terraform Format"
        run: "terraform fmt -check"
        continue-on-error: true
      - 
        id: init
        name: "Terraform Init"
        run: "terraform init"
      - 
        id: validate
        name: "Terraform Validate"
        run: "terraform validate -no-color"
      - 
        id: plan
        if: "github.event_name == 'pull_request'"
        name: "Terraform Plan"
        run: "terraform plan -no-color"
        continue-on-error: true
      - 
        name: Slack Notifications
        uses: actions/slack@v1
        with:
            status: ${{ job.plan }}
            steps: ${{ tojson(steps) }}
            channel: 'Sanjay Soni'
        if: always()
      - 
        if: "steps.plan.outcome == 'failure'"
        name: "Terraform Plan Status"
        run: "exit 1"
      - 
        if: "github.ref == 'refs/heads/main' && github.event_name == 'push'"
        name: "Terraform Apply"
        run: "terraform apply -auto-approve"
        

     

