name: "Terraform"

on:
  push:
    branches:
      - main
  pull_request:

jobs: 
  terraform: 
    name: Terraform
    runs-on: ubuntu-latest
    steps: 
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        env: 
         AWS_ACCESS_KEY_ID: "${{ env.AWS_ACCESS_KEY_ID }}"
         AWS_SECRET_ACCESS_KEY: "${{ env.AWS_SECRET_ACCESS_KEY }}"
        name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v1
      - 
        id: fmt
        name: "Terraform Format"
        run: "terraform fmt -check"
        continue-on-error: true
      - 
        env: 
          AWS_ACCESS_KEY_ID: "${{ env.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ env.AWS_SECRET_ACCESS_KEY }}"
        name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v1
      - 
        id: init
        name: "Terraform Init"
        run: "terraform init"
      - 
        env: 
         AWS_ACCESS_KEY_ID: "${{ env.AWS_ACCESS_KEY_ID }}"
         AWS_SECRET_ACCESS_KEY: "${{ env.AWS_SECRET_ACCESS_KEY }}"
        name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v1
      - 
        id: validate
        name: "Terraform Validate"
        run: "terraform validate -no-color"
      - 
        id: plan
        if: "github.event_name == 'pull_request'"
        name: "Terraform Plan"
        run: "terraform plan -no-color"
        continue-on-error: true
      - 
        env: 
          AWS_ACCESS_KEY_ID: "${{ env.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ env.AWS_SECRET_ACCESS_KEY }}"
        name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v1
      - 
        if: "steps.plan.outcome == 'failure'"
        name: "Terraform Plan Status"
        run: "exit 1"
      - 
        if: "github.ref == 'refs/heads/main' && github.event_name == 'push'"
        name: "Terraform Apply"
        run: "terraform apply -auto-approve"
      - 
        env: 
          AWS_ACCESS_KEY_ID: "${{ env.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ env.AWS_SECRET_ACCESS_KEY }}"
        name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v1

